GET http://localhost:3000/data
###
GET http://localhost:3000/data/1
###
POST http://localhost:3000/data
Content-Type: application/json

{
    "id": "3",
    "Firstname": "New",
    "Surname": "User"
}
###
POST http://localhost:3000/doc
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "jk",
    "password": "sala"
}