GET http://localhost:3000/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImprIiwiaWF0IjoxNzMyMDQ3MDI5LCJleHAiOjE3MzIwNTA2Mjl9.Q3Jhv4YwT6CmrUqYFVSd1NVu0DNQPvhUxlsEeqwXzTA
###
GET http://localhost:3000/data/1
###
POST http://localhost:3000/data
Content-Type: application/json

{
    "id": "3",
    "Firstname": "New",
    "Surname": "User"
}
###
POST http://localhost:3000/doc
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "jk",
    "password": "sala"
}